### PR TITLE
Fix nbconvert pin on CI and fix requirements matplotlib pin.

### PR DESCRIPTION
**Pull request by erykoff**

### CODE REVIEW

**Comment by erykoff** [comment]
@beckermr This replaces #59 where I also fixed the CI.

**Review by beckermr — CHANGES_REQUESTED** [review]
You have requirements listed ~3 times. We should adjust the CI to use the requirements.txt, move the dev / test requirements to a separate file, and possibly have the setup.cfg read requirements from a file via (I think) `install_requires = file: requirements.txt`

**Comment by beckermr** [comment]
If you'd like, I can submit a PR moving the whole project over the `pyproject.toml`. Despite my distaste for all of this new fangled stuff, it is actually very nice to put everything in one single file and is now working pretty well.

**Comment by erykoff** [comment]
If you want to combine this with a pyproject.toml thing that would be great.

**Comment by erykoff** [comment]
FYI, I have found in the past that it is necessary to do the tests (not all, but some) with both conda forge and pypi versions because of annoying matplotlib font issues.

**Pull request closed without merging**
