### PR TITLE
U/wmwv/plot ellipse

### LINKED ISSUE #27: Add ability to plot ellipses
I'd like to add the ability to plot ellipses.  The path forward seems to be to add and `skyaxes.ellipse` function next to the `skyaxes.circle` function 

https://github.com/LSSTDESC/skyproj/blob/d46052ee9cda7277b06bcc008ea022ba66518757/skyproj/skyaxes.py#L233

The key is then to figure out what the `dist` argument should be as a function of `az` in the call to `geod.fwd`

Does the following seem basically right?

```
    def circle(self, lon, lat, radius, nsamp=100, fill=False, **kwargs):
[...]
        az = np.linspace(360.0, 0.0, nsamp)
        lons, lats, _ = geod.fwd(
            np.full(nsamp, lon, dtype=np.float64),
            np.full(nsamp, lat, dtype=np.float64),
            az,
            np.full(nsamp, radius_m)
        )
```

```
    def ellipse(self, lon, lat, a, b, theta, radius, nsamp=100, fill=False, **kwargs):
[...]
        az = np.linspace(360.0, 0.0, nsamp)
        pa_offset = 90  # Position Angle is defined as degrees East of North
        pa_offset_in_radians = np.deg2rad(pa_offset)
        phase_in_radians = np.deg2rad(az - theta - pa_offset)

        theta_in_radians = np.deg2rad(theta)
        rotated_x = a * np.cos(phase_in_radians)
        rotated_y = b * np.sin(phase_in_radians)
        x = rotated_x * np.cos(theta_in_radians - pa_offset_in_radians) - rotated_y * np.sin(theta_in_radians - pa_offset_in_radians)
        y = rotated_x * np.sin(theta_in_radians - pa_offset_in_radians) + rotated_y * np.cos(theta_in_radians - pa_offset_in_radians)
        dist = np.sqrt(x**2 + y**2)
        lons, lats, _ = geod.fwd(
            np.full(nsamp, lon, dtype=np.float64),
            np.full(nsamp, lat, dtype=np.float64),
            az,
            dist,
        )
```

### PR DESCRIPTION
**Pull request by wmwv**
Add `ellipse` as a type to plot analogous to `circle`.

Visually tested.  I did not actually measure the resulting ellipses.

I also added `ellipse` to `tests/test_lines_polynomials.py`.  I have visually inspected the plot and the new ellipses and they look right.

But all of the image comparison tests fail for me when I run them locally anyway This was true on the main branch before making any changes.  I probably don't have the exact environment set up to pixel-by-pixel recreate the matplotlib plots.

Resolves #27

### CODE REVIEW

**Comment by wmwv** [comment]
Hmmm... just realized that matplotlib patch.Ellipse expects major and minor axis instead of semi-major and semi-minor axis.  Which convention would be less surprising here?

**Comment by erykoff** [comment]
Well, I have to say that specifying circles by radius and ellipses by width/height is strange.  But what do I know?

**Comment by wmwv** [comment]
OK, based on a sample size of 2, let's say that astronomers would find semi-major and semi-minor axes less surprising.

**Comment by erykoff** [comment]
I am concerned that you aren't getting the tests to pass locally.  I have them pass on multiple envs, and the tests should be insulated from any `.matplotlibrc` that you have.  Can you post one of the failed diffs?  (Maybe on a separate issue).

**Review by erykoff — APPROVED** [review]
Looks good.  Is it worth adding an ellipse to the example plotting at https://skyproj.readthedocs.io/en/latest/basic_interface.html#drawing-lines-and-polygons ?

**Comment by wmwv** [comment]
Posted diff on #29 
Will follow-up there.

**Pull request merged**
